// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CurrencyPreset {
    /**
     * Creates a new CurrencyPreset instance.
     * @param {Partial<CurrencyPreset>} [$$source = {}] - The source object to create the CurrencyPreset.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("symbol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["symbol"] = "";
        }
        if (!("denominations" in $$source)) {
            /**
             * @member
             * @type {PresetDenomination[]}
             */
            this["denominations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrencyPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CurrencyPreset}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("denominations" in $$parsedSource) {
            $$parsedSource["denominations"] = $$createField2_0($$parsedSource["denominations"]);
        }
        return new CurrencyPreset(/** @type {Partial<CurrencyPreset>} */($$parsedSource));
    }
}

export class PresetDenomination {
    /**
     * Creates a new PresetDenomination instance.
     * @param {Partial<PresetDenomination>} [$$source = {}] - The source object to create the PresetDenomination.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value_cents"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetDenomination instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetDenomination}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetDenomination(/** @type {Partial<PresetDenomination>} */($$parsedSource));
    }
}

export class SettingsInput {
    /**
     * Creates a new SettingsInput instance.
     * @param {Partial<SettingsInput>} [$$source = {}] - The source object to create the SettingsInput.
     */
    constructor($$source = {}) {
        if (!("store_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_name"] = "";
        }
        if (!("currency_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currency_label"] = "";
        }
        if (!("currency_symbol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currency_symbol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput(/** @type {Partial<SettingsInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PresetDenomination.createFrom;
const $$createType1 = $Create.Array($$createType0);
