// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CurrencyPreset {
    "label": string;
    "symbol": string;
    "denominations": PresetDenomination[] | null;
}

export interface PresetDenomination {
    "label": string;
    "value_cents": number;
    "kind": string;
}

export interface SettingsInput {
    "store_name": string;
    "currency_label": string;
    "currency_symbol": string;
}
