// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service backs store info and currency presets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<store$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2789967688).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CurrencyPreset[]>}
 */
export function ListCurrencyPresets() {
    return $Call.ByID(1241180500).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.SettingsInput} $in
 * @returns {$CancellablePromise<store$0.Settings>}
 */
export function SaveSettings($in) {
    return $Call.ByID(3642096403, $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = store$0.Settings.createFrom;
const $$createType1 = $models.CurrencyPreset.createFrom;
const $$createType2 = $Create.Array($$createType1);
