// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service backs store info and currency presets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(2789967688);
}

export function ListCurrencyPresets(): $CancellablePromise<$models.CurrencyPreset[] | null> {
    return $Call.ByID(1241180500);
}

export function SaveSettings($in: $models.SettingsInput): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(3642096403, $in);
}
