// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DenominationInput {
    "id": string;
    "label": string;
    "value_cents": number;
    "kind": string;
    "sort_order": number;
    "active": boolean;
}
