// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages the configurable denomination list.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns denominations ordered bills → coins. Pass activeOnly to hide
 * disabled rows (count screen); settings passes false to edit everything.
 */
export function List(activeOnly: boolean): $CancellablePromise<store$0.Denomination[] | null> {
    return $Call.ByID(3817116880, activeOnly);
}

/**
 * SaveAll replaces the denomination list. Rows still referenced by history are
 * deactivated instead of deleted so past counts stay intact.
 */
export function SaveAll($in: $models.DenominationInput[] | null): $CancellablePromise<store$0.Denomination[] | null> {
    return $Call.ByID(3599457732, $in);
}
