// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages the configurable denomination list.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns denominations ordered bills → coins. Pass activeOnly to hide
 * disabled rows (count screen); settings passes false to edit everything.
 * @param {boolean} activeOnly
 * @returns {$CancellablePromise<store$0.Denomination[]>}
 */
export function List(activeOnly) {
    return $Call.ByID(3817116880, activeOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveAll replaces the denomination list. Rows still referenced by history are
 * deactivated instead of deleted so past counts stay intact.
 * @param {$models.DenominationInput[]} $in
 * @returns {$CancellablePromise<store$0.Denomination[]>}
 */
export function SaveAll($in) {
    return $Call.ByID(3599457732, $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = store$0.Denomination.createFrom;
const $$createType1 = $Create.Array($$createType0);
