// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Count {
    "id": string;
    "created_at": string;
    "type": string;
    "expected_cents": number;
    "counted_cents": number;
    "drops_cents": number;
    "variance_cents": number;
    "note": string;
}

/**
 * CountDetail is the full immutable snapshot returned for detail views.
 */
export interface CountDetail {
    "id": string;
    "created_at": string;
    "type": string;
    "expected_cents": number;
    "counted_cents": number;
    "drops_cents": number;
    "variance_cents": number;
    "note": string;
    "items": CountItem[] | null;
    "drops": CountDrop[] | null;
}

export interface CountDrop {
    "id": string;
    "count_id": string;
    "amount_cents": number;
    "note": string;
    "created_at": string;
}

export interface CountItem {
    "id": string;
    "count_id": string;
    "denomination_id": string;
    "denomination_label": string;
    "value_cents": number;
    "quantity": number;
    "subtotal_cents": number;
}

export interface Denomination {
    "id": string;
    "label": string;
    "value_cents": number;
    "kind": string;
    "sort_order": number;
    "active": boolean;
}

export interface Settings {
    "id": number;
    "store_name": string;
    "currency_label": string;
    "currency_symbol": string;
}
