// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Count {
    /**
     * Creates a new Count instance.
     * @param {Partial<Count>} [$$source = {}] - The source object to create the Count.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("expected_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expected_cents"] = 0;
        }
        if (!("counted_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["counted_cents"] = 0;
        }
        if (!("drops_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["drops_cents"] = 0;
        }
        if (!("variance_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["variance_cents"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Count instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Count}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Count(/** @type {Partial<Count>} */($$parsedSource));
    }
}

/**
 * CountDetail is the full immutable snapshot returned for detail views.
 */
export class CountDetail {
    /**
     * Creates a new CountDetail instance.
     * @param {Partial<CountDetail>} [$$source = {}] - The source object to create the CountDetail.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("expected_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expected_cents"] = 0;
        }
        if (!("counted_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["counted_cents"] = 0;
        }
        if (!("drops_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["drops_cents"] = 0;
        }
        if (!("variance_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["variance_cents"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {CountItem[]}
             */
            this["items"] = [];
        }
        if (!("drops" in $$source)) {
            /**
             * @member
             * @type {CountDrop[]}
             */
            this["drops"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CountDetail}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField8_0($$parsedSource["items"]);
        }
        if ("drops" in $$parsedSource) {
            $$parsedSource["drops"] = $$createField9_0($$parsedSource["drops"]);
        }
        return new CountDetail(/** @type {Partial<CountDetail>} */($$parsedSource));
    }
}

export class CountDrop {
    /**
     * Creates a new CountDrop instance.
     * @param {Partial<CountDrop>} [$$source = {}] - The source object to create the CountDrop.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("count_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["count_id"] = "";
        }
        if (!("amount_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amount_cents"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountDrop instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CountDrop}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CountDrop(/** @type {Partial<CountDrop>} */($$parsedSource));
    }
}

export class CountItem {
    /**
     * Creates a new CountItem instance.
     * @param {Partial<CountItem>} [$$source = {}] - The source object to create the CountItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("count_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["count_id"] = "";
        }
        if (!("denomination_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["denomination_id"] = "";
        }
        if (!("denomination_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["denomination_label"] = "";
        }
        if (!("value_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value_cents"] = 0;
        }
        if (!("quantity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quantity"] = 0;
        }
        if (!("subtotal_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["subtotal_cents"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CountItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CountItem(/** @type {Partial<CountItem>} */($$parsedSource));
    }
}

export class Denomination {
    /**
     * Creates a new Denomination instance.
     * @param {Partial<Denomination>} [$$source = {}] - The source object to create the Denomination.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value_cents"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Denomination instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Denomination}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Denomination(/** @type {Partial<Denomination>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("store_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_name"] = "";
        }
        if (!("currency_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currency_label"] = "";
        }
        if (!("currency_symbol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currency_symbol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CountItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CountDrop.createFrom;
const $$createType3 = $Create.Array($$createType2);
