// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CountDropInput {
    "amount_cents": number;
    "note": string;
}

export interface CountFilter {
    "type": string;
    "from": string;
    "to": string;
    "limit": number;
    "offset": number;
}

export interface CountItemInput {
    "denomination_id": string;
    "quantity": number;
}

export interface CreateCountInput {
    "type": string;
    "expected_cents": number;
    "note": string;
    "items": CountItemInput[] | null;
    "drops": CountDropInput[] | null;
}
