// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CountDropInput {
    /**
     * Creates a new CountDropInput instance.
     * @param {Partial<CountDropInput>} [$$source = {}] - The source object to create the CountDropInput.
     */
    constructor($$source = {}) {
        if (!("amount_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amount_cents"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountDropInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CountDropInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CountDropInput(/** @type {Partial<CountDropInput>} */($$parsedSource));
    }
}

export class CountFilter {
    /**
     * Creates a new CountFilter instance.
     * @param {Partial<CountFilter>} [$$source = {}] - The source object to create the CountFilter.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CountFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CountFilter(/** @type {Partial<CountFilter>} */($$parsedSource));
    }
}

export class CountItemInput {
    /**
     * Creates a new CountItemInput instance.
     * @param {Partial<CountItemInput>} [$$source = {}] - The source object to create the CountItemInput.
     */
    constructor($$source = {}) {
        if (!("denomination_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["denomination_id"] = "";
        }
        if (!("quantity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quantity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CountItemInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CountItemInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CountItemInput(/** @type {Partial<CountItemInput>} */($$parsedSource));
    }
}

export class CreateCountInput {
    /**
     * Creates a new CreateCountInput instance.
     * @param {Partial<CreateCountInput>} [$$source = {}] - The source object to create the CreateCountInput.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("expected_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expected_cents"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {CountItemInput[]}
             */
            this["items"] = [];
        }
        if (!("drops" in $$source)) {
            /**
             * @member
             * @type {CountDropInput[]}
             */
            this["drops"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateCountInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateCountInput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        if ("drops" in $$parsedSource) {
            $$parsedSource["drops"] = $$createField4_0($$parsedSource["drops"]);
        }
        return new CreateCountInput(/** @type {Partial<CreateCountInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CountItemInput.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CountDropInput.createFrom;
const $$createType3 = $Create.Array($$createType2);
