// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service records counts, history and CSV exports.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateCount validates the input, computes totals and persists count + items
 * + drops in a single transaction. Variance = counted + drops - expected.
 */
export function CreateCount($in: $models.CreateCountInput): $CancellablePromise<store$0.CountDetail> {
    return $Call.ByID(3641477939, $in);
}

/**
 * DeleteCount removes a count and its items/drops (CASCADE).
 */
export function DeleteCount(id: string): $CancellablePromise<void> {
    return $Call.ByID(1053414578, id);
}

/**
 * ExportCountCSV writes a per-count CSV into the exports subdir of the
 * app-data dir and returns the path.
 */
export function ExportCountCSV(id: string): $CancellablePromise<string> {
    return $Call.ByID(179066071, id);
}

/**
 * ExportHistoryCSV writes the full count history into the exports subdir of
 * the app-data dir and returns the path.
 */
export function ExportHistoryCSV(): $CancellablePromise<string> {
    return $Call.ByID(4209180278);
}

/**
 * GetCount returns the full immutable detail of one count.
 */
export function GetCount(id: string): $CancellablePromise<store$0.CountDetail> {
    return $Call.ByID(1707766155, id);
}

/**
 * ListCounts returns count summaries, newest first.
 */
export function ListCounts(f: $models.CountFilter): $CancellablePromise<store$0.Count[] | null> {
    return $Call.ByID(4032956228, f);
}

/**
 * RestoreCount re-inserts a previously deleted count with its original IDs,
 * timestamps and totals, so delete-undo is a true restore rather than a new
 * count. Denomination snapshots travel with the items, so current settings
 * are left untouched.
 */
export function RestoreCount(d: store$0.CountDetail): $CancellablePromise<store$0.CountDetail> {
    return $Call.ByID(3782248545, d);
}
