// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service records counts, history and CSV exports.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateCount validates the input, computes totals and persists count + items
 * + drops in a single transaction. Variance = counted + drops - expected.
 * @param {$models.CreateCountInput} $in
 * @returns {$CancellablePromise<store$0.CountDetail>}
 */
export function CreateCount($in) {
    return $Call.ByID(3641477939, $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteCount removes a count and its items/drops (CASCADE).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCount(id) {
    return $Call.ByID(1053414578, id);
}

/**
 * ExportCountCSV writes a per-count CSV into the exports subdir of the
 * app-data dir and returns the path.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ExportCountCSV(id) {
    return $Call.ByID(179066071, id);
}

/**
 * ExportHistoryCSV writes the full count history into the exports subdir of
 * the app-data dir and returns the path.
 * @returns {$CancellablePromise<string>}
 */
export function ExportHistoryCSV() {
    return $Call.ByID(4209180278);
}

/**
 * GetCount returns the full immutable detail of one count.
 * @param {string} id
 * @returns {$CancellablePromise<store$0.CountDetail>}
 */
export function GetCount(id) {
    return $Call.ByID(1707766155, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListCounts returns count summaries, newest first.
 * @param {$models.CountFilter} f
 * @returns {$CancellablePromise<store$0.Count[]>}
 */
export function ListCounts(f) {
    return $Call.ByID(4032956228, f).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RestoreCount re-inserts a previously deleted count with its original IDs,
 * timestamps and totals, so delete-undo is a true restore rather than a new
 * count. Denomination snapshots travel with the items, so current settings
 * are left untouched.
 * @param {store$0.CountDetail} d
 * @returns {$CancellablePromise<store$0.CountDetail>}
 */
export function RestoreCount(d) {
    return $Call.ByID(3782248545, d).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = store$0.CountDetail.createFrom;
const $$createType1 = store$0.Count.createFrom;
const $$createType2 = $Create.Array($$createType1);
